services:

  frontend:
    image: zix3011/sos-navigator-frontend:latest
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    image: zix3011/sos-navigator-backend:latest
    restart: always
    ports:
      - "3002:3002"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /home/projektUser/deploy.sh:/deploy.sh:ro
    extra_hosts:
    - "host.docker.internal:host-gateway"